version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Check security using Yarn Audit"
          command: |
            make check-sec
      - run:
          name: "Build files"
          command: |
            yarn cache clean
            yarn global add react-scripts
            make install
            make build
